### ISSUE TITLE
mapTo is not a function after upgrading to rxjs 5.5.2 and angular 5.1

### ISSUE THREAD

**Issue by billyjacobs2014** [redux-observable/redux-observable#362]
**Do you want to request a *feature* or report a *bug*?**  
BUG

**What is the current behavior?**
I am getting the following error:
 ERROR TypeError: action$.ofType(...).mapTo is not a function.

Despcription of problem:
I upgraded to Angular 5.1, which requires rxjs 5.5.2. I have an epic in a module that is lazy loaded. On ngInit of the the component, I add all of the new epics from my lazy loaded module. When my module loads I get the following: ERROR TypeError: action$.ofType(...).mapTo is not a function.. The error occurs when the epic is being added to my stream of epics. If I don't load the one epic that uses mapTo in this module, then my code works. 

Here is the offending epic:
clearWatchbillArtifactApprovalWorkflowEpic() { 
return action$ => action$ .ofType(WatchbillViewerActions.SET_WATCHBILL_ROUTED) .mapTo({type: WatchbillViewerActions.CLEAR_WATCHBILL_ARTIFACT_APPROVAL_WORKFLOW.SUCCESS}); 
}

NOTE: I explicitly added import { mapTo } from 'rxjs/operators'; in my modules epics.ts file, to see if that would resolve the issue but it did not.  I also tried adding import 'rxjs' in my root index.ts file. 

**What is the expected behavior?**
No errors. 

**Which versions of redux-observable, and which browser and OS are affected by this issue? Did this work in previous versions of redux-observable?**
I am using rxjs 5.5.2, Angular 5.1, Chrome Version 61.0.3163.100. It works in rxjs 5.4.2 and Angular 4.4.

**Comment by billyjacobs2014** [comment]
Ok. I figured out a solution. I replaced the following in my epic.ts file. 

import { mapTo } from 'rxjs/operators';
with 
import 'rxjs/add/operator/mapTo';

Why is that. I also tried import 'rxjs' which did not work.

**Comment by jayphelps** [comment]
hmm are you 100% sure 5.5.2 of rxjs is installed? did you check `node_modules/rxjs/package.json` version field? This sounds like this recent rxjs issue https://github.com/ReactiveX/rxjs/issues/2984 but it was supposed to be fixed starting in 5.5.1 so perhaps it's come back with a vengeance. Can you possibly provide a simple example repo for us to reproduce? We'll probably want to move this convo over to https://github.com/ReactiveX/rxjs/issues/2984

**Comment by billyjacobs2014** [comment]
I am 100% sure. I checked node_modules/rxjs/package.js and it is version 5.5.2. I made sure that in all of my projects, I triple verified that I have the same versions of all referenced node packages as well. I have been trying to upgrade to Angular 5.1/ rxjs 5.5.2 for a week with different issues. Building a repro might be tricky but I will try. I just noticed additional strange behavior which I have not completely identified. I have one project which is a control project. It is referenced by another project which is my main application as described above (I have multiple main applications that reference the control project). If I attach events from my parent application to @Output event emitters in control application, I get an error saying:  "Uncaught (in promise): TypeError: Cannot read property 'subscribe' of undefined". After further investigation I found that all of my @Input and @Outpus in my child control have null values inside of ngOnInit. I checked this by console.logging the values of the control component's members. Upgrading to Angular 5 with rxjs 5.5.2 has been interesting.

**Comment by jayphelps** [comment]
Gotcha. Thanks for confirming! 😄  I won't likely be able to help further without a way to easily reproduce it. If I did, I could probably find the issue in seconds. I would pause the debugger when the error occurs and examine what the prototype looks like and inspect all the bundles to confirm there is only one copy of rxjs; if you are sure you're importing the operator its **extremely likely** there are two, one the operator is getting added to the and the other redux-observable is extending for ActionsObservable. In newer versions of webpack it shows inline the file path of the imports on disk, which I would use to then deduce why there are two copies.

**Comment by billyjacobs2014** [comment]
FYI: Here are all of the rxjs imports in the common control library project:
![image](https://user-images.githubusercontent.com/8147585/32753469-8eeaef7a-c892-11e7-8760-e136930f8317.png)
AND Here are all of the rxjs imports in the main application using the common control library project
![image](https://user-images.githubusercontent.com/8147585/32753662-57e329b0-c893-11e7-92c8-15cea1c8362b.png)

**Comment by billyjacobs2014** [comment]
Also, if it would be helpful, I am willing to setup a join me and show you what is happening. In the mean time, I will attempt to reproduce in anther small prototype project I have.

**Comment by billyjacobs2014** [comment]
I have a repro project. Don't delete the node_modules folder because it contains the package from the common controls project. Just npm install the rest of the packages.  So there are 2 issues. 
1. If you run it with only ng serve then you will get an error when it launches immediately. 
Unexpected value 'SomeModuleInControlProject' imported by the module 'SomeModuleImportedInMainProject'. Please add a @NgModule annotation
2. If you run it with ng serve --aot, that error goes away. Once you get it running, just click on the edit icon (pencil) and you will see the kind of error I described where the event emitters and other properties of the controls referenced from the common control project are all null. 

You may need to comment out the reference to the commoncontrols project in the package.json since it won't be in the location specified. I can send you the source for the second project if you need it. 

[JAB.Structures.Portal.zip](https://github.com/redux-observable/redux-observable/files/1469422/JAB.Structures.Portal.zip)

**Comment by billyjacobs2014** [comment]
@jayphelps let me know if you need any additional information.

**Comment by billyjacobs2014** [comment]
@jayphelps were you able to get the reproduction project running and debug?

**Comment by jayphelps** [comment]
@billyjacobs2014 not yet. Sorry for the delay! This is something I do in my free time. 😄

**Comment by billyjacobs2014** [comment]
Cool. No problem. So how does that work? Is this just open source and there are volunteers that work on issues?

**Comment by jayphelps** [comment]
@billyjacobs2014 yup this is just a community project at this point. The redux-observable itself is pretty tiny and battle tested, so bugs inside redux-observable itself are pretty rare. Most of the effort I put in is support related and most are RxJS questions. 🎉

**Comment by billyjacobs2014** [comment]
Hi @jayphelps,

I have resolved the issues above. See this chain:

https://github.com/angular/angular/issues/20375#issuecomment-345197141

**Comment by jayphelps** [comment]
@billyjacobs2014 great to hear! thanks for letting me know. 🕺
